fahrplan/website/views/trips.py
from time import time
from flask import Blueprint, flash, jsonify, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import date, time

from website.model.line import Recurrence
from website.model.user import User
from .. import db
from ..model import Line, Trip

from website.data.dummy_data import trains as dummy_trains


trips = Blueprint("trips", __name__)


@trips.route("/trips/", methods=["GET", "POST"])
@login_required
def trips_view():
    """View function to show all trips"""
    trips = Trip.query.all()
    return render_template("trips/trips.html", user=current_user, trips=trips)


@trips.route("/lines/<int:line_id>/create_trip/", methods=["GET", "POST"])
@login_required
def trip_create(line_id):
    """View function to create new trip in wizard style"""

    line = Line.query.get(line_id)
    if not line:
        flash(f"Fahrtstrecke ID {line_id} nicht vorhanden!", category="error")
        return redirect(request.referrer)
    users = None
    # create new trip object with line_id
    trip = Trip(line_parent=Line.query.get(line_id))

    # trains DUMMY data
    trains = dummy_trains
    # trains = filter(lambda t: t["spurweite"] == line.route.sections[0].track, trains)

    secprices = [sec.section.fee for sec in line.sections]
    price_min = sum(secprices) * 100
    trip.price = price_min

    if request.method == "POST":
        #  get all input form data
        note = request.form.get("note", default="", type=str)
        departure = request.form.get("departure", default="00:00", type=str)
        price = request.form.get("price", default=0, type=int)
        recurring = request.form.get("recurring", default=None, type=int)
        date_single = request.form.get("date", default=None, type=str)
        date_start = request.form.get("date_start", default=None, type=str)
        date_end = request.form.get("date_end", default=None, type=str)

        mon = request.form.get("mon", default=0, type=int)
        tue = request.form.get("tue", default=0, type=int)
        wed = request.form.get("wed", default=0, type=int)
        thu = request.form.get("thu", default=0, type=int)
        fri = request.form.get("fri", default=0, type=int)
        sat = request.form.get("sat", default=0, type=int)
        sun = request.form.get("sun", default=0, type=int)

        train_id = request.form.get("train_id", default=None, type=int)
        personell = request.form.getlist("personell")
        confirm = request.form.get("confirm", default=False, type=bool)

        # set attributes from form data
        trip.note = note

        if len(departure) < 2:
            # ensure 2 digits, time.fromisoformat won't accept single digit
            departure = f"0{departure}"
        trip.departure = time.fromisoformat(departure)

        trip.price = max(price_min, price * 100)

        recurrence = Recurrence(
            mon=1,
            tue=1,
            wed=1,
            thu=1,
            fri=1,
            sat=1,
            sun=1,
        )

        if recurring == 0 and date_single is not None:
            date_single = date.fromisoformat(date_single)
            recurrence.date_start = date_single
            recurrence.date_end = date_single
        elif date_start and date_end is not None:
            date_start = date.fromisoformat(date_start)
            date_end = date.fromisoformat(date_end)
            recurrence.date_start = date_start
            recurrence.date_end = date_end
            recurrence.mon = mon
            recurrence.tue = tue
            recurrence.wed = wed
            recurrence.thu = thu
            recurrence.fri = fri
            recurrence.sat = sat
            recurrence.sun = sun
        trip.recurrence = recurrence

        # TODO: get only available trains
        # trains = filter(lambda t: not trip.is_train_in_use(t["id"]), trains)

        # step 2
        if train_id:
            trip.train_id = train_id
            with db.session.no_autoflush:
                # TODO: get only available Users
                users = User.query.all()

        # step 3
        resolved = []
        if personell:
            # print(f"personell: {personell}")
            with db.session.no_autoflush:
                # trip.personell = [(user for user_id in personell for user in User.query.get(user_id))]
                for user_id in personell:
                    user = User.query.get(user_id)
                    if user:
                        trip.personell.append(user)

            resolved = trip.get_resolved_all_dict()
            resolved = sorted(resolved, key=lambda d: d["date"])

            db.session.flush()

        # step final
        if confirm:
            db.session.add(trip)
            db.session.commit()
            flash("Durchführung angelegt!", category="success")
            return redirect(url_for("lines.line_detail", line_id=line.id))

        return render_template(
            "trips/trip_c.html",
            current_user=current_user,
            line=line,
            recurring=recurring,
            trip=trip,
            resolved=resolved,
            recurrence=recurrence,
            trains=trains,
            users=users,
        )

    recurring = None
    return render_template(
        "trips/trip_c.html", current_user=current_user, trip=trip, line=line
    )


@trips.route("/trip/<int:trip_id>/update/", methods=["GET", "POST"])
@login_required
def trip_update(trip_id):
    """WIP: View function to update a trip"""
    # TODO
    trip = Trip.query.get(trip_id)
    return render_template(
        "trips/trip_c.html",
        current_user=current_user,
        trip=trip,
        line=trip.line_parent,
    )


@trips.route("/trip/<int:trip_id>/delete/", methods=["GET", "POST"])
@login_required
def trip_delete(trip_id):
    """View function to delete a trip"""
    trip = Trip.query.get(trip_id)
    if trip:
        db.session.delete(trip)
        db.session.commit()
        flash(f"Durchführungen gelöscht!", category="success")
        return redirect(request.referrer)
    flash(f"Durchführung nicht vorhanden!", category="error")
    return redirect(request.referrer)

fahrplan/website/templates/trips/trip_c.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Durchführung anlegen{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif current_user.admin == 1 %}


<form method="post">
    <br>
    <h1>Durchführung anlegen</h1>
    <br>

    <h5>Auf Fahrtstrecke: {{ trip.line_parent.descr }}
    </h5>

    <div class="form-group">

        <!-- step 1 - recurrence -->
        <label for="note">Notiz:</label>
        <input class="form-control"
               id="note"
               name="note"
               type="text"
               value="{{ trip.note if trip.note }}">

        <label for="departure">Abfahrtszeit:</label>
        <input class="form-control"
               id="departure"
               name="departure"
               required=""
               value="{{ trip.departure if trip.departure }}">
        <br>
        <fieldset>
            <!-- <legend>Select a maintenance drone:</legend> -->
            <input type="radio"
                   id="single"
                   name="recurring"
                   value="0"
                   {{ "checked" if recurring == 0}}>
            <label for="single">Einzelfahrt</label>

            <input type="radio"
                   id="recurring"
                   name="recurring"
                   value="1"
                   {{ "checked" if recurring == 1}}>
            <label for="recurring">Intervall</label>

        </fieldset>
        <br>

        {% if recurring == 0 %}
        <label for="single">Einzelfahrt</label>
        <table id="single">
            <tbody>
                <tr>
                    <th><label for=date">Datum:</label></th>
                    <td><input id="date"
                               name="date"
                               type="date"
                               required=""
                               value="{{ recurrence.date_start }}"></td>
                </tr>
            </tbody>
        </table>
        {% elif recurring == 1 %}
        <label for="recurrence">Intervall</label>
        <table id="recurrence">
            <tbody>
                <tr>
                    <th><label for=date_start">Startdatum:</label></th>
                    <td><input id="date_start"
                               name="date_start"
                               type="date"
                               required=""
                               value="{{ recurrence.date_start }}"></td>
                </tr>
                <tr>
                    <th><label for="date_end">Enddatum:</label></th>
                    <td><input id="date_end"
                               name="date_end"
                               type="date"
                               required=""
                               value="{{ recurrence.date_end }}"></td>
                </tr>
                <tr>
                    <th><label for="mon">Montag:</label></th>
                    <td><input id="mon"
                               name="mon"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.mon }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="tue">Dienstag:</label></th>
                    <td><input id="tue"
                               name="tue"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.tue }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="wed">Mittwoch:</label></th>
                    <td><input id="wed"
                               name="wed"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.wed }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="thu">Donnerstag:</label></th>
                    <td><input id="thu"
                               name="thu"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.thu == True }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="fri">Freitag:</label></th>
                    <td><input id="fri"
                               name="fri"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.fri }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="sat">Samstag:</label></th>
                    <td><input id="sat"
                               name="sat"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.sat }}
                               value="1"></td>
                </tr>
                <tr>
                    <th><label for="sun">Sonntag:</label></th>
                    <td><input id="sun"
                               name="sun"
                               type="checkbox"
                               {{ 'checked=""' if recurrence.sun }}
                               value="1"></td>
                </tr>
            </tbody>
        </table>
        {% endif %}

        <br>
        <label for="price">Preis (Mindestpreis {{ (trip.price/100)|int }})</label>
        <input class="form-control"
               id="price"
               name="price"
               type="number"
               min="{{ (trip.price/100) |int }}"
               value="{{ (trip.price/100) |int }}">

        <!-- step 2 -->
        {% if trip.recurrence %}
        <br>
        <label for="train_id">Zug</label>
        <select class="form-control"
                id="train_id"
                name="train_id">
            {%for t in trains %}
            <option value="{{ t.id }}"
                    {{ 'selected' if t.id == trip.train_id }}
                    {{ 'disabled' if (t["spurweite"] != line.route.sections[0].track) }}>
                        {{ t.id }} - {{t.bezeichnung}} ({{ t.spurweite }}) {# '(in Verwendung)' if t.in_use #}
                    </option>
            {% endfor %}
        </select>
        <br>
        {% if trip.train_id %}
        <br>

        <!-- step 3 -->
        <label for="personell">Personal:</label>
        <select class="form-control"
                id="personell"
                multiple="multiple"
                name="personell"
                size="8">
            {% for u in users %}
            <option value="{{ u.id }}"
                    {{ 'selected' if (u in trip.personell)}}>{{ u.id }}{{ u.last_name }}</option>
            {% endfor %}
        </select>
        <br>


        {% endif %}
        {% endif %}

        <button type="submit"
                class="btn btn-primary">Weiter</button>

        <br>
        <hr>
        <br>
        {% if trip.personell %}
        <h2>Vorschau:</h2>

        {% include 'trips/trips_component.html' %}
        <br>
        <h3>Neue Durchführungen</h3>
        {% include 'trips/trips_resolved_component.html' %}


        <label for="confirm">Alles richtig? </label>
        <input type="checkbox"
               class="form-check-input"
               id="confirm"
               name="confirm"
               placeholder="confirm">
        <br><br>
        <button type="submit"
                class="btn btn-primary">Speichern</button>
        {% endif %}



    </div>
</form>



{% endif %}
{% endblock %}

fahrplan/website/templates/trips/trips.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrplan bearbeiten{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif current_user.admin == 1 %}

<br />
<br />

<form method="post">

    {% if not update %}

    <a href="update"
       class="btn btn-outline-primary">Fahrtstrecke bearbeiten</a>

    {% else %}

    <p>line.id: {{ line.id if line != undefined or None }}</p>
    <p>line.route.name: {{line.route.name}}</p>

    <div class="form-group">
        <label for="route_id">Wähle Strecke</label>
        <select name="route_id"
                class="form-select"
                id="route_id"
                disabled>
            <option value="{{ line.route.id }}">{{ line.route.name }}</option>
        </select>

        <label for="descr">Beschreibung</label>
        <input type="text"
               class="form-control"
               id="descr"
               name="descr"
               value="{{ line.descr if line.descr }}"
               placeholder="Beschreibung" />

        <label for="price">Gesamtpreis</label>
        <input type="text"
               class="form-control"
               id="price"
               name="price"
               value="{{ line.price if line.price }}"
               placeholder="cent" />

        {% if line.sections is not undefined or None %}
        <label for="first_section">Startbahnhof</label>
        <select name="first_section"
                class="form-select"
                id="first_section">
            {% for section in line.route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if (line.sections|first).section.id == section.id }}>
                {{ section.from_station_name }}</option>
            {% endfor %}
        </select>
        {% endif %}

        {% if line.sections != undefined or None %}
        <label for="last_section">Endbahnhof</label>
        <select name="last_section"
                class="form-select"
                id="last_section">
            {% for section in line.route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if (line.sections|last).section.id == section.id }}>
                {{ section.to_station_name }}</option>
            {% endfor %}
        </select>
        {% endif %}


        <br />

        <button type="submit"
                class="btn btn-primary">Weiter</button>
        {% endif %}
        <!-- endif not update -->

        {% if line is not undefined or None %}
        {% if line.route is not undefined or None %}
        <table class="table">
            <thead>
                <tr>
                    <td colspan="5"
                        style="padding-top: 2em;">
                        <h2>{{ line.descr }} </h2>
                        <h5>auf {{ line.route.name }}</h5>
                        <span>Gesamtpreis: {{ "{:,.2f}".format(line.price/100) | replace('.',',') }} €</span>
                        <p>Fahrtdauer: {{ (line.sections | last).arrival }} min</p>
                        <p>Information: {{ line.note if line.note }}</p>
                        <br><br>
                        <h5>Abschnitte:</h5>
                    </td>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <th scope="col">#</th>
                    <th scope="col">von</th>
                    <th scope="col">nach</th>
                    <th scope="col">Dauer (min)</th>
                    <th scope="col">Kumuliert (min)</th>
                </tr>
                {% if line.sections %}
                {% for line_section in line.sections %}
                <tr>
                    <td>{{ line_section.section.id }}</td>
                    <td>{{ line_section.section.from_station_name }}</td>
                    <td>{{ line_section.section.to_station_name }}</td>
                    <td>{{ line_section.section.duration }} min</td>
                    <td>{{ line_section.arrival }} min</td>
                </tr>
                {% endfor %}
                <tr>
                    {% else %}
                <tr>
                    <td colspan="11">Keine Durchführungen</td>
                </tr>
                {% endif %}

                </tr>
            </tbody>
        </table>
        <br>

        {% if update %}
        <label for="confirm">Alles richtig? </label>
        <input type="checkbox"
               class="form-check-input"
               id="confirm"
               name="confirm"
               placeholder="confirm" />
        <br><br>
        <button type="submit"
                class="btn btn-primary">Speichern</button>

        {% endif %}
        {% endif %}
        {% endif %}


        {% if sortby == 'date' %}
        <table class="table">
            <thead>
                <tr>
                    <td colspan="8"
                        style="padding-top: 0em;">
                        <h6>Einzeldurchführungen:</h6>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="col">L</th>
                    <th scope="col">B</th>
                    <th scope="col">I-ID</th>
                    <th scope="col">Datum</th>
                    <th scope="col">ab</th>
                    <th scope="col">an</th>
                    <th scope="col">Zug</th>
                    <th scope="col">Personal</th>
                </tr>
                {% for r in resolved %}
                <tr>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>
                        {{r.rec_id}}
                    </td>
                    <td>
                        {{r.date}}
                    </td>
                    <td>
                        {{r.departure}}
                    </td>
                    <td>
                        {{r.departure}}
                    </td>
                    <td>
                        {{r.train_id}}
                    </td>
                    <td>
                        {% for p in r.personell %}
                        <span style="border: 1px;">{{p}}</span>
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}

                {% else %}
                <tr>
                    <td colspan="11">Keine Durchführungen</td>
                </tr>
                {% endif %}
            </tbody>
        </table>




    </div>
</form>

{% endif %}
{% endblock %}

fahrplan/website/templates/trips/trips_component.html
<table class="table">
    <thead>
        <tr>
            <td {% if current_user.admin ==1 %}
                colspan="12"
                {% else %}
                colspan="10"
                {% endif %}
                style="padding-top: 2em;">
                <!-- <h5>Durchführungen:</h5> -->
            </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th></th>
            {% if current_user.admin ==1 %}
            <th scope="col">B</th>
            <th scope="col">L</th>
            {% endif %}
            <th scope="col">Preis</th>
            <th scope="col">Von</th>
            <th scope="col">Bis</th>
            <th scope="col">Mo</th>
            <th scope="col">Di</th>
            <th scope="col">Mi</th>
            <th scope="col">Do</th>
            <th scope="col">Fr</th>
            <th scope="col">Sa</th>
            <th scope="col">So</th>
        </tr>

        {% if line.trips %}
        {% for t in line.trips %}
        <tr>
            {% if current_user.admin ==1 %}
            <td>{{ ('+ ' if t.id == trip.id) if trip }}</td>
            <td>
                <!-- deactivated -->
                <a {# href="{{ url_for('trips.trip_update', trip_id=t.id) }}" #}
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x270E;</span>
                </a>
            </td>
            <td>
                <a href="{{ url_for('trips.trip_delete', trip_id=t.id) }}"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                    <!-- <span aria-hidden="true">&#x1f5d1;</span> -->
                </a>
            </td>
            {% endif %}
            <td>{{ "{:,.2f}".format(t.price/100) | replace('.',',') }} €</td>
            <td>{{ t.recurrence.date_start }}</td>
            <td>{{ t.recurrence.date_end }}</td>
            <td>{{ t.departure if t.recurrence.mon }}</td>
            <td>{{ t.departure if t.recurrence.tue }}</td>
            <td>{{ t.departure if t.recurrence.wed }}</td>
            <td>{{ t.departure if t.recurrence.thu }}</td>
            <td>{{ t.departure if t.recurrence.fri }}</td>
            <td>{{ t.departure if t.recurrence.sat }}</td>
            <td>{{ t.departure if t.recurrence.sun }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="11">Keine Durchführungen</td>
        </tr>
        {% endif %}
    </tbody>
</table>

fahrplan/website/templates/trips/trips_resolved_component.html
<table class="table">
    <thead>
        <tr>
            <td colspan="8"
                style="padding-top: 0em;">
                <h6>Einzeldurchführungen:</h6>
            </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Fahrtstrecke</th>
            <th scope="col">Notiz</th>
            <th scope="col">Von</th>
            <th scope="col">Nach</th>
            <th scope="col" style="text-align: right; padding-right: 2em;">^Datum</th>
            <th scope="col">ab</th>
            <th scope="col">an</th>
            <th scope="col">Zug</th>
            <th scope="col">Personal</th>
        </tr>
        {% if resolved %}
        {% for r in resolved %}
        <tr >
            <td>
                <a href="{{ url_for('lines.line_detail', line_id=r.line.id) }}">{{r.line.descr}}</a>
            </td>
            <td>
                {{r.note}}
            </td>
            <td>
                {{(r.line.sections | first).section.from_station_name}}
            </td>
            <td>
                {{(r.line.sections | last).section.to_station_name}}
            </td>
            <td style="text-align: right; padding-right: 2em;">
                {{(r.date).strftime('%A %d.%m.%Y')}} {#r.date|format_date(format='full', locale='fr_FR') #}
            </td>
            <td>
                {{r.departure}}
            </td>
            <td>
                {{r.arrival}}
            </td>
            <td>
                {{r.train_id}}
            </td>
            <td>
                {% set comma = joiner("-") %}
                {% for p in r.personell %}
                {{ comma() }} <span style="padding: 2px; border: 1px solid;">{{p}}</span>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="11">Keine Durchführungen</td>
        </tr>
        {% endif %}
    </tbody>
</table>