fahrplan/website/views/users.py
import datetime
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .. import db
from ..model import User

# from random import randrange
# from lorem_text import lorem


users = Blueprint("users", __name__)


@users.route("/users/", methods=["GET"])
@login_required
def users_view():
    all_users = User.query.all()
    all_users = sorted(all_users, key=lambda u: u.id)
    # all_users.sort()
    return render_template(
        "users/users.html", current_user=current_user, users=all_users
    )


@users.route("/users/<int:user_id>/trips", methods=["GET"])
@login_required
def user_trips(user_id):
    """View function to show all trips of a given User, 
    accepts URL parameter ?show=future to hide past trips"""
    
    show = request.args.get("show", default="all")  # future
    # sortby = request.args.get("sortby", default="date")  # line

    user = User.query.get(user_id)
    trips = user.trips

    resolved = []
    for trip in trips:
        resolved.extend(trip.get_resolved_all_dict())

    if show == "future":
        resolved = filter(lambda rt: rt["date"] >= datetime.date.today(), resolved)

    # if sortby == "line":
    #     resolved = sorted(resolved, key=lambda rt: rt["line"])
    # else:
    #     resolved = sorted(resolved, key=lambda rt: rt["date"])

    return render_template(
        "users/user_trips.html", current_user=current_user, resolved=resolved, user=user
    )


@users.route("/users/<int:user_id>/update", methods=["GET", "POST"])
@login_required
def user_update(user_id):
    """View function to update a given User"""
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        last_name = request.form.get("lastName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        admin = request.form.get("admin")
        old_pw = request.form.get("oldPW")

        user = User.query.get(user_id)
        print(password2)

        if not user:
            flash("User nicht vorhanden")
        elif len(email) < 4:
            flash("E-Mail zu kurz (<3)", category="error")
        elif len(first_name) < 2:
            flash("Name zu kurz (<2)", category="error")
        elif len(last_name) < 2:
            flash("Name zu kurz (<2)", category="error")
        elif current_user.admin == 0:
            if check_password_hash(user.password, old_pw) != True:
                flash("Aktuelles Passwort falsch!", category="error")
                # return redirect(request.referrer)
                # ?
        elif (
            password1 == None or password1 == "" and password2 == ""
        ):  # pw fields empty
            user.update(email, first_name, last_name, admin)
            db.session.commit()
            flash("Benutzer bearbeitet!", category="success")
            return redirect(url_for("users.users"))
            # return redirect(request.referrer)

        elif password1 != password2:
            flash("Pw stimmt nicht überein", category="error")
        elif len(password1) < 3:
            flash("PW zu kurz(<3)", category="error")
            # return redirect(request.referrer)
        else:
            user.update(
                email,
                first_name,
                last_name,
                admin,
                generate_password_hash(password1, method="sha256"),
            )
            db.session.commit()
            flash("Benutzer bearbeitet!", category="success")
            # return redirect(url_for("users.users"))
            return redirect(request.referrer)
    user = User.query.get(user_id)
    print(user)
    return render_template("users/users_c_u.html", current_user=current_user, user=user)


@users.route("/users/create", methods=["GET", "POST"])
@login_required
def user_create():
    """View function to create a new User"""
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        last_name = request.form.get("lastName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        admin = request.form.get("admin")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email in Benutzung", category="error")
            return redirect(request.referrer)
        elif len(email) < 4:
            flash("E-Mail zu kurz (<3)", category="error")
            return redirect(request.referrer)
        elif len(first_name) < 2:
            flash("Name zu kurz (<1)", category="error")
            return redirect(request.referrer)
        elif password1 != password2:
            flash("Pw stimmt nicht überein", category="error")
            return redirect(request.referrer)
        elif len(password1) < 3:
            flash("PW zu kurz(<3)", category="error")
            return redirect(request.referrer)
        else:
            new_user = User(
                email=email,
                first_name=first_name,
                last_name=last_name,
                admin=admin,
                password=generate_password_hash(password1, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            flash("Benutzer angelegt!", category="success")
        return redirect(url_for("users.users_view"))
    return render_template(
        "users/users_c_u.html", current_user=current_user, user=False
    )


@users.route("/users/<int:user_id>/delete", methods=["GET"])
@login_required
def user_delete(user_id):
    """View function to delete a User"""
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash("Benutzer entfernt!", category="success")
        return redirect(url_for("users.users_view"))
    flash(f"Benutzer ID {user_id} nicht vorhanden!", category="error")
    return redirect(url_for("users.users_view"))

fahrplan/website/templates/users/user_trips.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrplan{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% else %}
<div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
        <h1 class="py-4">Fahrtdurchführungen - {{user}}</h1>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        <a href="{{ url_for('users.user_trips', user_id=user.id, show='all') }}"
           id="btn-showall"
           class="btn btn-outline-primary mx-2"
           aria-label="Show All">
            <span aria-hidden="true">Alle anzeigen</span>
        </a>
        <a href="{{ url_for('users.user_trips', user_id=user.id, show='future') }}"
           id="btn-edit"
           class="btn btn-outline-primary mx-2"
           aria-label="Edit">
            <span aria-hidden="true">Zukünftige anzeigen</span>
        </a>
    </div>
</div>

<div>
    {% if resolved %}
    {% include 'trips/trips_resolved_component.html' %}
    {% else %}
    <p>Keine Fahrten</p>
    {% endif %}
</div>

{% endif %}
{% endblock %}

fahrplan/website/templates/users/users.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Personal{% endblock %}
{% block content %}

{% if current_user.admin == 1 %}

<div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
        <h1 class="py-4">Personal</h1>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        {% if current_user.admin == 1 %}
        <a href="{{ url_for('users.user_create') }}"
           class="btn btn-outline-primary">Neuen Personalaccount hinzufügen</a>
        {% endif %}
    </div>
</div>
<div>

<table class="table">
    <thead>
        <tr>
            <!-- <th scope="col">&#x1F511;</th> -->
            <th scope="col">&#x2666;</th>
            <th scope="col">#</th>
            <th scope="col">Vorname</th>
            <th scope="col">Nachname</th>
            <th scope="col">Email</th>
            <th scope="col">Geburtsdatum</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for u in users %}
        <tr>
            {% if u.admin == 1 %}
            <!-- <td><span><i class="fa-solid fa-key"></i></span></td> -->
            <td>&#x1F511;</td>
            <!-- <td>&#x1F510;</td> -->
            {% else %}
            <td></td>
            {% endif %}
            <th scope="row"
                data-id="{{ u.id }}">{{ u.id }}</th>
            <td data-id="{{ u.id }}">{{ u.first_name }}</td>
            <td data-id="{{ u.id }}">{{ u.last_name }}</td>
            <td data-id="{{ u.id }}">{{ u.email }}</td>
            <td data-id="{{ u.id }}">{{ u.birthday }}</td>
            <td>
                <a href="{{ url_for('users.user_trips', user_id=u.id) }}"
                   id="btn-trips"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Fahrten">
                    <span aria-hidden="true">Fahrten</span>
                </a>
            </td>
            <td>
                <a href="{{ url_for('users.user_update', user_id=u.id) }}"
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x270E;</span>
                </a>
            </td>
            <td>
                <a href="{{ url_for('users.user_delete', user_id=u.id) }}"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                    <!-- <span aria-hidden="true">&#x1f5d1;</span> -->
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>
    Keine Berechtigung
</p>
{% endif %}
</div>
{% endblock %}

fahrplan/website/templates/users/users_c_u.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Personal{% endblock %}
{% block content %}
{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif not user %}
<form method="post">
    <br />
    <h3>Personal anlegen</h3>
    <br />
    <div class="form-group">
        <label for="email">E-Mail-Adresse</label>
        <input type="email"
               class="form-control"
               id="email"
               name="email"
               placeholder="Email Addresse" />
        <label for="firstName">Vorname</label>
        <input type="text"
               class="form-control"
               id="firstName"
               name="firstName"
               placeholder="Vorname" />
        <label for="lastName">Nachname</label>
        <input type="text"
               class="form-control"
               id="lastName"
               name="lastName"
               placeholder="Nachname" />
        <label for="password1">Passwort</label>
        <input type="password"
               class="form-control"
               id="password1"
               name="password1"
               placeholder="Passwort" />
        <label for="password2">Passwort wiederholen</label>
        <input type="password"
               class="form-control"
               id="password2"
               name="password2"
               placeholder="Passwort wiederholen" />
        <label for="admin">Admin</label>
        <input type="checkbox"
               class="form-check-input"
               id="admin"
               name="admin"
               placeholder="Admin" />
        <br />
        <button type="submit"
                class="btn btn-primary">Submit</button>
    </div>
</form>
{% else %}
<form method="post">
    <br />
    <h3>Personal bearbeiten</h3>
    <br />
    <div class="form-group">
        <label for="email">E-Mail-Addresse</label>
        <input type="email"
               class="form-control"
               id="email"
               name="email"
               placeholder=""
               value="{{ user.email }}" />
        <label for="firstName">Vorname</label>
        <input type="text"
               class="form-control"
               id="firstName"
               name="firstName"
               placeholder=""
               value="{{ user.first_name }}" />
        <label for="lastName">Nachname</label>
        <input type="text"
               class="form-control"
               id="lastName"
               name="lastName"
               placeholder=""
               value="{{ user.last_name }}" />
        <label for="password1">Neues Passwort</label>
        <input type="password"
               class="form-control"
               id="password1"
               name="password1"
               placeholder="Neues Passwort" />
        <label for="password2">Neues Passwort wiederholen</label>
        <input type="password"
               class="form-control"
               id="password2"
               name="password2"
               placeholder="Neues Passwort wiederholen" />
        {% if current_user.admin == 1 %}
        <label for="admin">Admin</label>
        <input type="checkbox"
               class="form-check-input"
               id="admin"
               name="admin"
               placeholder="Admin"
               {% if user.admin == 1 %}checked{% endif %} />
        {% endif %}
        <br />
        {% if current_user.admin == 0 %}
        <label for="oldPW">Derzeitiges Passwort bestätigen</label>
        <input type="password"
               class="form-control"
               id="oldPW"
               name="oldPW"
               placeholder="Derzeitiges Passwort bestätigen" />
        <br />
        {% endif %}
        <button type="submit"
                class="btn btn-primary">Submit</button>
    </div>
</form>
{% endif %}
{% endblock %}