fahrplan/website/views/lines.py
import json
import os
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import and_
import requests

from website.model.line import LineSection, Trip
from .. import db
from ..model import Section, Line, Route


lines = Blueprint("lines", __name__)


# @admin_required  #TODO custom decorator ??
@lines.route("/lines/", methods=["GET", "POST"])
@login_required
def lines_view():
    """View function: show all lines"""
    lines = Line.query.all()
    lines = sorted(lines, key=lambda l: l.route.id)
    return render_template("lines/lines.html", current_user=current_user, lines=lines)


@lines.route("/lines/<int:line_id>/", methods=["GET", "POST"])
@login_required
def line_detail(line_id):
    """View function: show line details page by id"""
    line = Line.query.get(line_id)
    return render_template(
        "lines/line_detail.html", current_user=current_user, line=line
    )


@lines.route("/lines/create/", methods=["GET", "POST"])
# @lines.route("/lines/<int:line_id>/update", methods=["GET", "POST"])
@login_required
def line_create():
    """View function: page to create a new line"""
    if request.method == "POST":
        route_id = request.form.get("route_id", default=None, type=int)
        descr = request.form.get("descr", default=None, type=str)
        note = request.form.get("note", default=None, type=str)
        # price = request.form.get("price", default=None, type=int)

        first_section = request.form.get("first_section", default=None, type=int)
        last_section = request.form.get("last_section", default=None, type=int)

        confirm = request.form.get("confirm", default=False, type=bool)

        sel_route = Route.query.get(route_id)
        line = None



        # step 2
        if first_section and last_section:
            linesections = []
            arrival = 0
            for s in range(first_section, last_section + 1):
                section = Section.query.get(s)
                arrival += section.duration
                linesections.append(LineSection(arrival=arrival, section=section))

                secprices = [sec.section.fee for sec in linesections]
                price_min = sum(secprices) * 100

            line = Line(
                descr=descr,
                note=note,
                price=price_min,
                route=Route.query.get(route_id),
                sections=linesections,
            )
            print(line)
        # step final
        if confirm:
            db.session.add(line)
            db.session.commit()
            flash("Fahrtstrecke angelegt!", category="success")
            return redirect(url_for("lines.line_detail", line_id=line.id))

        routes = Route.query.all()
        return render_template(
            "lines/line_c.html",
            current_user=current_user,
            routes=routes,
            sel_route=sel_route,
            descr=descr,
            # price=price,
            first_section=first_section,
            last_section=last_section,
            line=line,
        )

    url = os.environ.get("STRECKEN_API_URL")
    try:
        res = requests.get(url).content
        routes = json.loads(res)["routes"]
        for r in routes:
            r = Route.dict_to_obj(r)
            db_route = Route.query.get(r.id)
            print(db_route)
            if not db_route:
                db.session.add(r)
        db.session.commit()
        flash("Streckendaten erfolgreich geladen!", category="success")
    except requests.exceptions.RequestException as e:
        flash(f"Streckendaten laden fehlgeschlagen!", category="error")
        flash(f"- {e}", category="error")

    routes = Route.query.all()
    return render_template(
        "lines/line_c.html",
        current_user=current_user,
        routes=routes,
    )


@lines.route("/lines/<int:line_id>/update/", methods=["GET", "POST"])
@login_required
def line_update(line_id):
    """View function: update page for given line by ID"""
    if request.method == "POST":
        route_id = request.form.get("route_id", default=None, type=int)
        descr = request.form.get("descr", default=None, type=str)
        note = request.form.get("note", default=None, type=str)
        # price = request.form.get("price", default=None, type=int)

        first_section = request.form.get("first_section", default=None, type=int)
        last_section = request.form.get("last_section", default=None, type=int)

        confirm = request.form.get("confirm", default=False, type=bool)

        sel_route = Route.query.get(route_id)
        line = Line.query.get(line_id)

        if first_section == last_section + 1:
            flash("Start und Endbahnhof dürfen nicht gleich sein!", category="error")
        elif first_section > last_section + 1:
            flash(
                "Startbahnhof darf nicht vor dem Endbahnhof liegen!", category="error"
            )
        elif first_section and last_section:
            linesections = []
            arrival = 0
            for s in range(first_section, last_section + 1):
                section = Section.query.get(s)
                arrival += section.duration
                linesections.append(LineSection(arrival=arrival, section=section))
                secprices = [sec.section.fee for sec in linesections]
                price_min = sum(secprices) * 100

            print(linesections)
            if not linesections:
                flash("Keine Sections!", category="error")
            else:
                line.update(
                    descr=descr,
                    price=price_min,
                    note=note,
                    sections=linesections,
                )
                print(line)

            if confirm:
                db.session.commit()
                flash("Fahrtstrecke bearbeitet!", category="success")
                return redirect(url_for("lines.line_detail", line_id=line.id))

        routes = Route.query.all()
        return render_template(
            "lines/line_u.html",
            current_user=current_user,
            routes=routes,
            sel_route=sel_route,
            descr=descr,
            # price=price,
            first_section=first_section,
            last_section=last_section,
            line=line,
        )

    line = Line.query.get(line_id)
    return render_template(
        "lines/line_u.html", current_user=current_user, line=line, update=True
    )


@lines.route("/lines/<int:line_id>/delete/", methods=["GET", "POST"])
@login_required
def line_delete(line_id):
    """View function to delete a given line by ID"""
    # TODO
    line = Line.query.get(line_id)
    if line:
        db.session.delete(line)
        db.session.commit()
        flash("Fahrtstrecke entfernt!", category="success")
        return redirect(url_for("lines.lines_view"))

    return render_template(
        "lines/line_detail.html", current_user=current_user, line=line, update=True
    )


#
# TRIPS


@lines.route("/lines/<int:line_id>/resolved/", methods=["GET", "POST"])
@login_required
def line_detail_trips_resolved(line_id):
    """View function to show line details page with all individual trips"""
    # TODO pages for individual trips
    # /lines/7/?trips=intervals
    # /lines/7/?trips=resolved&recurrence_id=2&items=20&page=1

    # sortby = request.args.get("sortby", default="date")
    # page = request.args.get("page", type=int, default=1)
    # items = request.args.get("items", type=int, default=10)
    # i = (page - 1) * items

    line = Line.query.get(line_id)
    trips = Trip.query.filter(
        and_(
            Trip.line_id == line_id,
            # Trip.departure >= t_dep,
        )
    )
    # .slice(i, i + items)

    resolved = []
    for trip in trips:
        resolved.extend(trip.get_resolved_all_dict())

    resolved = sorted(resolved, key=lambda d: d["date"])
    return render_template(
        "lines/line_detail.html",
        current_user=current_user,
        line=line,
        trips=trips,
        resolved=resolved,
    )

fahrplan/website/views/trips.py
from time import time
from flask import Blueprint, flash, jsonify, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import date, time

from website.model.line import Recurrence
from website.model.user import User
from .. import db
from ..model import Line, Trip

from website.data.dummy_data import trains as dummy_trains


trips = Blueprint("trips", __name__)


@trips.route("/trips/", methods=["GET", "POST"])
@login_required
def trips_view():
    """View function to show all trips"""
    trips = Trip.query.all()
    return render_template("trips/trips.html", user=current_user, trips=trips)


@trips.route("/lines/<int:line_id>/create_trip/", methods=["GET", "POST"])
@login_required
def trip_create(line_id):
    """View function to create new trip in wizard style"""

    line = Line.query.get(line_id)
    if not line:
        flash(f"Fahrtstrecke ID {line_id} nicht vorhanden!", category="error")
        return redirect(request.referrer)
    users = None
    # create new trip object with line_id
    trip = Trip(line_parent=Line.query.get(line_id))

    # trains DUMMY data
    trains = dummy_trains
    # trains = filter(lambda t: t["spurweite"] == line.route.sections[0].track, trains)

    secprices = [sec.section.fee for sec in line.sections]
    price_min = sum(secprices) * 100
    trip.price = price_min

    if request.method == "POST":
        #  get all input form data
        note = request.form.get("note", default="", type=str)
        departure = request.form.get("departure", default="00:00", type=str)
        price = request.form.get("price", default=0, type=int)
        recurring = request.form.get("recurring", default=None, type=int)
        date_single = request.form.get("date", default=None, type=str)
        date_start = request.form.get("date_start", default=None, type=str)
        date_end = request.form.get("date_end", default=None, type=str)

        mon = request.form.get("mon", default=0, type=int)
        tue = request.form.get("tue", default=0, type=int)
        wed = request.form.get("wed", default=0, type=int)
        thu = request.form.get("thu", default=0, type=int)
        fri = request.form.get("fri", default=0, type=int)
        sat = request.form.get("sat", default=0, type=int)
        sun = request.form.get("sun", default=0, type=int)

        train_id = request.form.get("train_id", default=None, type=int)
        personell = request.form.getlist("personell")
        confirm = request.form.get("confirm", default=False, type=bool)

        # set attributes from form data
        trip.note = note

        if len(departure) < 2:
            # ensure 2 digits, time.fromisoformat won't accept single digit
            departure = f"0{departure}"
        trip.departure = time.fromisoformat(departure)

        trip.price = max(price_min, price * 100)

        recurrence = Recurrence(
            mon=1,
            tue=1,
            wed=1,
            thu=1,
            fri=1,
            sat=1,
            sun=1,
        )

        if recurring == 0 and date_single is not None:
            date_single = date.fromisoformat(date_single)
            recurrence.date_start = date_single
            recurrence.date_end = date_single
        elif date_start and date_end is not None:
            date_start = date.fromisoformat(date_start)
            date_end = date.fromisoformat(date_end)
            recurrence.date_start = date_start
            recurrence.date_end = date_end
            recurrence.mon = mon
            recurrence.tue = tue
            recurrence.wed = wed
            recurrence.thu = thu
            recurrence.fri = fri
            recurrence.sat = sat
            recurrence.sun = sun
        trip.recurrence = recurrence

        # TODO: get only available trains
        # trains = filter(lambda t: not trip.is_train_in_use(t["id"]), trains)

        # step 2
        if train_id:
            trip.train_id = train_id
            with db.session.no_autoflush:
                # TODO: get only available Users
                users = User.query.all()

        # step 3
        resolved = []
        if personell:
            # print(f"personell: {personell}")
            with db.session.no_autoflush:
                # trip.personell = [(user for user_id in personell for user in User.query.get(user_id))]
                for user_id in personell:
                    user = User.query.get(user_id)
                    if user:
                        trip.personell.append(user)

            resolved = trip.get_resolved_all_dict()
            resolved = sorted(resolved, key=lambda d: d["date"])

            db.session.flush()

        # step final
        if confirm:
            db.session.add(trip)
            db.session.commit()
            flash("Durchführung angelegt!", category="success")
            return redirect(url_for("lines.line_detail", line_id=line.id))

        return render_template(
            "trips/trip_c.html",
            current_user=current_user,
            line=line,
            recurring=recurring,
            trip=trip,
            resolved=resolved,
            recurrence=recurrence,
            trains=trains,
            users=users,
        )

    recurring = None
    return render_template(
        "trips/trip_c.html", current_user=current_user, trip=trip, line=line
    )


@trips.route("/trip/<int:trip_id>/update/", methods=["GET", "POST"])
@login_required
def trip_update(trip_id):
    """WIP: View function to update a trip"""
    # TODO
    trip = Trip.query.get(trip_id)
    return render_template(
        "trips/trip_c.html",
        current_user=current_user,
        trip=trip,
        line=trip.line_parent,
    )


@trips.route("/trip/<int:trip_id>/delete/", methods=["GET", "POST"])
@login_required
def trip_delete(trip_id):
    """View function to delete a trip"""
    trip = Trip.query.get(trip_id)
    if trip:
        db.session.delete(trip)
        db.session.commit()
        flash(f"Durchführungen gelöscht!", category="success")
        return redirect(request.referrer)
    flash(f"Durchführung nicht vorhanden!", category="error")
    return redirect(request.referrer)

fahrplan/website/templates/lines/line_c.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrtstrecke anlegen{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif current_user.admin == 1 %}

<form method="post">
    <br />
    <h1>Fahrtstrecke anlegen</h1>
    <br />

    <div class="form-group">

        <label for="route_id">Wähle Strecke</label>
        <select name="route_id"
                class="form-select"
                id="route_id">
            {% for route in routes %}
            <option value="{{ route.id }}"
                    {{ 'selected' if sel_route and sel_route.id == route.id }}>{{ route.name }}</option>
            {% endfor %}
        </select>

        <label for="descr">Name der Fahrtstrecke</label>
        <input type="text"
               class="form-control"
               id="descr"
               name="descr"
               value="{{ descr if descr }}"
               placeholder="Name der Fahrtstrecke" />

        <label for="note">Information</label>
        <textarea type="text"
                  class="form-control"
                  id="note"
                  name="note"
                  placeholder="">{{ note if note }}</textarea>

        {% if sel_route is not undefined or None %}
        <label for="first_section">Startbahnhof</label>
        <select name="first_section"
                class="form-select"
                id="first_section">
            {% for section in sel_route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if first_section == section.id }}>
                {{ section.from_station_name }}</option>
            {% endfor %}
        </select>
        {% endif %}

        {% if last_section != undefined or None %}
        <label for="last_section">Endbahnhof</label>
        <select name="last_section"
                class="form-select"
                id="last_section">
            {% for section in sel_route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if last_section == section.id }}>
                {{ section.to_station_name }}</option>
            {% endfor %}
        </select>
        {% endif %}


        <br />
        <button type="submit"
                class="btn btn-primary">Weiter</button>
    </div>

    <br><br>
    <h5>Vorschau:</h5>

    {% if line is not undefined or None %}
    {% if line.route is not undefined or None %}
    {% include 'lines/line_component.html' %}
    <br>
    <label for="confirm">Alles richtig? </label>
    <input type="checkbox"
           class="form-check-input"
           id="confirm"
           name="confirm"
           placeholder="confirm" />
    <br><br>
    <button type="submit"
            class="btn btn-primary">Speichern</button>
    {% endif %}
    {% endif %}
</form>

{% endif %}
{% endblock %}

fahrplan/website/templates/lines/line_component.html
<section id="fahrtstrecke"
         style="border: 1px solid; padding: 0.5em; margin-top: 1em;">
    <table class="table">

        <thead>
            <tr>
                <td colspan="5">
                    <h2>{{ line.descr }} </h2>
                    <h5>auf {{ line.route.name }}</h5>
                    <span>Gesamtpreis: {{ "{:,.2f}".format(line.price/100) | replace('.',',') }} €</span>
                    <p>Fahrtdauer: {{ (line.sections | last).arrival }} min</p>
                    <p>Information: {{ line.note if line.note }}</p>
                    <br>
                    <h5>Abschnitte:</h5>
                </td>
            </tr>
        </thead>

        <tbody>

            <tr>
                <th scope="col">#</th>
                <th scope="col">von</th>
                <th scope="col">nach</th>
                <th scope="col">Dauer (min)</th>
                <th scope="col">Kumuliert (min)</th>
            </tr>

            {% if line.sections %}
            {% for line_section in line.sections %}
            <tr>
                <td>{{ line_section.section.id }}</td>
                <td>{{ line_section.section.from_station_name }}</td>
                <td>{{ line_section.section.to_station_name }}</td>
                <td>{{ line_section.section.duration }} min</td>
                <td>{{ line_section.arrival }} min</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="11">Keine Abschnitte gewählt</td>
            </tr>
            {% endif %}

        </tbody>
    </table>
</section>

fahrplan/website/templates/lines/line_detail.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrplan bearbeiten{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif current_user %}

<div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
        <h1 class="py-4">Fahrtstrecke</h1>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        {% if current_user.admin == 1 %}
        <a href="update"
        
           class="btn btn-outline-primary">Fahrtstrecke bearbeiten</a>
        {% endif %}
    </div>
</div>

{% if line is not undefined or None %}
{% if line.route is not undefined or None %}
{% include 'lines/line_component.html' %}

<br />
<br />

<div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
        <h2>Durchführungen</h2>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        {% if resolved %}
        <a href="{{ url_for('lines.line_detail', line_id=line.id) }}"
        class="btn btn-outline-primary">Einzeldurchführungen ausblenden</a>
        {% else %}
        <a href="{{ url_for('lines.line_detail_trips_resolved', line_id=line.id) }}"
        class="btn btn-outline-primary">Einzeldurchführungen zeigen</a>
        {% endif %}
    </div>
    <div class="d-flex justify-content-end align-items-center">
        {% if current_user.admin == 1 %}
        <a href="{{ url_for('trips.trip_create', line_id=line.id) }}"
           class="btn btn-outline-primary">Durchführung hinzufügen</a>
        {% endif %}
    </div>
</div>
{% include 'trips/trips_component.html' %}

{% if resolved %}
{% include 'trips/trips_resolved_component.html' %}
{% endif %}

{% endif %}
{% endif %}
{% endif %}

{% endblock %}

fahrplan/website/templates/lines/line_u.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrtstrecke bearbeiten{% endblock %}
{% block content %}

{% if current_user == None %}
<!-- TODO if user not authenticated -->
<p>404</p>
{% elif current_user.admin == 1 %}

<form method="post">
    <br />
    <h1>Fahrtstrecke bearbeiten</h1>
    <br />

    <section id="update">

        <label for="route_id">Wähle Strecke</label>
        <select name="route_id"
                class="form-select"
                id="route_id"
                disabled>
            <option value="{{ line.route.id }}">{{ line.route.name }}</option>
        </select>

        <label for="descr">Name der Fahrstrecke</label>
        <input type="text"
               class="form-control"
               id="descr"
               name="descr"
               value="{{ line.descr if line.descr }}"
               placeholder="Name der Fahrstrecke" />

        <label for="note">Information</label>
        <textarea type="text"
                  class="form-control"
                  id="note"
                  name="note"
                  placeholder="">{{ note if note }}</textarea>


        <!-- Startbahnhof -->
        {% if line.sections is not undefined or None %}
        <label for="first_section">Startbahnhof</label>
        <select name="first_section"
                class="form-select"
                id="first_section">
            {% for section in line.route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if (line.sections|first).section.id == section.id }}>
                {{ section.from_station_name }}
            </option>
            {% endfor %}
        </select>
        {% endif %}

        <!-- Endbahnhof -->
        {% if line.sections != undefined or None %}
        <label for="last_section">Endbahnhof</label>
        <select name="last_section"
                class="form-select"
                id="last_section">
            {% for section in line.route.sections %}
            <option value="{{ section.id }}"
                    {{ 'selected' if (line.sections|last).section.id == section.id }}>
                {{ section.to_station_name }}
            </option>
            {% endfor %}
        </select>
        {% endif %}


        <br />
        <button type="submit"
                class="btn btn-primary">Vorschau aktualisieren</button>
    </section>

    <br><br>
    <h5>Vorschau:</h5>

    {% if line is not undefined or None %}
    {% if line.route is not undefined or None %}
    {% include 'lines/line_component.html' %}
    <br>
    <label for="confirm">Alles richtig? </label>
    <input type="checkbox"
           class="form-check-input"
           id="confirm"
           name="confirm"
           placeholder="confirm" />
    <br><br>
    <button type="submit"
            class="btn btn-primary">Speichern</button>
    {% endif %}
    {% endif %}
</form>
{% endif %}
{% endblock %}

fahrplan/website/templates/lines/lines.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrpläne{% endblock %}
{% block content %}

<div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
        <h1 class="py-4">Fahrtstrecken</h1>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        {% if current_user.admin == 1 %}
        <a href="create"
           class="btn btn-outline-primary">Neue Fahrtstrecke hinzufügen</a>
        {% endif %}
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Fahrtstrecke</th>
            <th scope="col">^ Strecke</th>
            <th scope="col">von</th>
            <th scope="col">nach</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for line in lines %}
        <tr>
            <th scope="row"
                data-id="{{ line.id }}">{{ line.id }}</th>
            <td data-id="{{ line.id }}">{{ line.descr }}</td>
            <td data-id="{{ line.id }}">{{ line.route.name }}</td>
            <td data-id="{{ line.id }}">{{ (line.sections | first).section.from_station_name }}</td>
            <td data-id="{{ line.id }}">{{ (line.sections | last).section.to_station_name }}</td>
            <td data-id="{{ line.id }}"> </td>
            <td>
                <a href="{{ url_for('lines.line_detail', line_id=line.id) }}"
                   id="btn-trips"
                   class="btn btn-sm btn-outline-primary"
                   aria-label="Fahrten">
                    <span aria-hidden="true">Fahrplan</span>
                </a>

            </td>
            {% if current_user.admin == 1 %}
            <td>
                <a href="{{ line.id }}/update"
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x270E;</span>
                </a>
            </td>
            <td>
                <a href="{{ line.id }}/delete"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}