fahrplan/website/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import LoginManager, current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from . import db
from .model import User


login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.login_message = "User needs to be logged in to view this page"
login_manager.login_message_category = "error"

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

# @login_manager. .....


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Angemeldet", category="success")
                login_user(user)  # remember=True)
                return redirect(url_for("views.index"))
            else:
                flash("Passwort falsch", category="error")
        else:
            flash("User nicht vorhanden", category="error")
    if current_user.is_authenticated:
        flash(f"{current_user.first_name} Bereits angemeldet", category="error")

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required  # cannot reach unless logged in
def logout():
    if current_user.id:
        logout_user()
        flash("Abgemeldet!", category="success")
    return redirect(url_for("auth.login"))

    # return render_template("home.html", isLogoutSuccessful=True, text="Erfolgreich abgemeldet")

fahrplan/website/views/index.py
from flask import Blueprint, render_template
from flask_login import current_user

from ..model import Line


index = Blueprint("index", __name__)


@index.route("/", methods=["GET"])
def index_view():
    lines = Line.query.all()
    return render_template("index.html", user=current_user, lines=lines)

fahrplan/website/views/lines.py
import json
import os
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import and_
import requests

from website.model.line import LineSection, Trip
from .. import db
from ..model import Section, Line, Route


lines = Blueprint("lines", __name__)


# @admin_required  #TODO custom decorator ??
@lines.route("/lines/", methods=["GET", "POST"])
@login_required
def lines_view():
    """View function: show all lines"""
    lines = Line.query.all()
    lines = sorted(lines, key=lambda l: l.route.id)
    return render_template("lines/lines.html", current_user=current_user, lines=lines)


@lines.route("/lines/<int:line_id>/", methods=["GET", "POST"])
@login_required
def line_detail(line_id):
    """View function: show line details page by id"""
    line = Line.query.get(line_id)
    return render_template(
        "lines/line_detail.html", current_user=current_user, line=line
    )


@lines.route("/lines/create/", methods=["GET", "POST"])
# @lines.route("/lines/<int:line_id>/update", methods=["GET", "POST"])
@login_required
def line_create():
    """View function: page to create a new line"""
    if request.method == "POST":
        route_id = request.form.get("route_id", default=None, type=int)
        descr = request.form.get("descr", default=None, type=str)
        note = request.form.get("note", default=None, type=str)
        # price = request.form.get("price", default=None, type=int)

        first_section = request.form.get("first_section", default=None, type=int)
        last_section = request.form.get("last_section", default=None, type=int)

        confirm = request.form.get("confirm", default=False, type=bool)

        sel_route = Route.query.get(route_id)
        line = None



        # step 2
        if first_section and last_section:
            linesections = []
            arrival = 0
            for s in range(first_section, last_section + 1):
                section = Section.query.get(s)
                arrival += section.duration
                linesections.append(LineSection(arrival=arrival, section=section))

                secprices = [sec.section.fee for sec in linesections]
                price_min = sum(secprices) * 100

            line = Line(
                descr=descr,
                note=note,
                price=price_min,
                route=Route.query.get(route_id),
                sections=linesections,
            )
            print(line)
        # step final
        if confirm:
            db.session.add(line)
            db.session.commit()
            flash("Fahrtstrecke angelegt!", category="success")
            return redirect(url_for("lines.line_detail", line_id=line.id))

        routes = Route.query.all()
        return render_template(
            "lines/line_c.html",
            current_user=current_user,
            routes=routes,
            sel_route=sel_route,
            descr=descr,
            # price=price,
            first_section=first_section,
            last_section=last_section,
            line=line,
        )

    url = os.environ.get("STRECKEN_API_URL")
    try:
        res = requests.get(url).content
        routes = json.loads(res)["routes"]
        for r in routes:
            r = Route.dict_to_obj(r)
            db_route = Route.query.get(r.id)
            print(db_route)
            if not db_route:
                db.session.add(r)
        db.session.commit()
        flash("Streckendaten erfolgreich geladen!", category="success")
    except requests.exceptions.RequestException as e:
        flash(f"Streckendaten laden fehlgeschlagen!", category="error")
        flash(f"- {e}", category="error")

    routes = Route.query.all()
    return render_template(
        "lines/line_c.html",
        current_user=current_user,
        routes=routes,
    )


@lines.route("/lines/<int:line_id>/update/", methods=["GET", "POST"])
@login_required
def line_update(line_id):
    """View function: update page for given line by ID"""
    if request.method == "POST":
        route_id = request.form.get("route_id", default=None, type=int)
        descr = request.form.get("descr", default=None, type=str)
        note = request.form.get("note", default=None, type=str)
        # price = request.form.get("price", default=None, type=int)

        first_section = request.form.get("first_section", default=None, type=int)
        last_section = request.form.get("last_section", default=None, type=int)

        confirm = request.form.get("confirm", default=False, type=bool)

        sel_route = Route.query.get(route_id)
        line = Line.query.get(line_id)

        if first_section == last_section + 1:
            flash("Start und Endbahnhof dürfen nicht gleich sein!", category="error")
        elif first_section > last_section + 1:
            flash(
                "Startbahnhof darf nicht vor dem Endbahnhof liegen!", category="error"
            )
        elif first_section and last_section:
            linesections = []
            arrival = 0
            for s in range(first_section, last_section + 1):
                section = Section.query.get(s)
                arrival += section.duration
                linesections.append(LineSection(arrival=arrival, section=section))
                secprices = [sec.section.fee for sec in linesections]
                price_min = sum(secprices) * 100

            print(linesections)
            if not linesections:
                flash("Keine Sections!", category="error")
            else:
                line.update(
                    descr=descr,
                    price=price_min,
                    note=note,
                    sections=linesections,
                )
                print(line)

            if confirm:
                db.session.commit()
                flash("Fahrtstrecke bearbeitet!", category="success")
                return redirect(url_for("lines.line_detail", line_id=line.id))

        routes = Route.query.all()
        return render_template(
            "lines/line_u.html",
            current_user=current_user,
            routes=routes,
            sel_route=sel_route,
            descr=descr,
            # price=price,
            first_section=first_section,
            last_section=last_section,
            line=line,
        )

    line = Line.query.get(line_id)
    return render_template(
        "lines/line_u.html", current_user=current_user, line=line, update=True
    )


@lines.route("/lines/<int:line_id>/delete/", methods=["GET", "POST"])
@login_required
def line_delete(line_id):
    """View function to delete a given line by ID"""
    # TODO
    line = Line.query.get(line_id)
    if line:
        db.session.delete(line)
        db.session.commit()
        flash("Fahrtstrecke entfernt!", category="success")
        return redirect(url_for("lines.lines_view"))

    return render_template(
        "lines/line_detail.html", current_user=current_user, line=line, update=True
    )


#
# TRIPS


@lines.route("/lines/<int:line_id>/resolved/", methods=["GET", "POST"])
@login_required
def line_detail_trips_resolved(line_id):
    """View function to show line details page with all individual trips"""
    # TODO pages for individual trips
    # /lines/7/?trips=intervals
    # /lines/7/?trips=resolved&recurrence_id=2&items=20&page=1

    # sortby = request.args.get("sortby", default="date")
    # page = request.args.get("page", type=int, default=1)
    # items = request.args.get("items", type=int, default=10)
    # i = (page - 1) * items

    line = Line.query.get(line_id)
    trips = Trip.query.filter(
        and_(
            Trip.line_id == line_id,
            # Trip.departure >= t_dep,
        )
    )
    # .slice(i, i + items)

    resolved = []
    for trip in trips:
        resolved.extend(trip.get_resolved_all_dict())

    resolved = sorted(resolved, key=lambda d: d["date"])
    return render_template(
        "lines/line_detail.html",
        current_user=current_user,
        line=line,
        trips=trips,
        resolved=resolved,
    )

fahrplan/website/views/users.py
import datetime
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .. import db
from ..model import User

# from random import randrange
# from lorem_text import lorem


users = Blueprint("users", __name__)


@users.route("/users/", methods=["GET"])
@login_required
def users_view():
    all_users = User.query.all()
    all_users = sorted(all_users, key=lambda u: u.id)
    # all_users.sort()
    return render_template(
        "users/users.html", current_user=current_user, users=all_users
    )


@users.route("/users/<int:user_id>/trips", methods=["GET"])
@login_required
def user_trips(user_id):
    """View function to show all trips of a given User, 
    accepts URL parameter ?show=future to hide past trips"""
    
    show = request.args.get("show", default="all")  # future
    # sortby = request.args.get("sortby", default="date")  # line

    user = User.query.get(user_id)
    trips = user.trips

    resolved = []
    for trip in trips:
        resolved.extend(trip.get_resolved_all_dict())

    if show == "future":
        resolved = filter(lambda rt: rt["date"] >= datetime.date.today(), resolved)

    # if sortby == "line":
    #     resolved = sorted(resolved, key=lambda rt: rt["line"])
    # else:
    #     resolved = sorted(resolved, key=lambda rt: rt["date"])

    return render_template(
        "users/user_trips.html", current_user=current_user, resolved=resolved, user=user
    )


@users.route("/users/<int:user_id>/update", methods=["GET", "POST"])
@login_required
def user_update(user_id):
    """View function to update a given User"""
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        last_name = request.form.get("lastName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        admin = request.form.get("admin")
        old_pw = request.form.get("oldPW")

        user = User.query.get(user_id)
        print(password2)

        if not user:
            flash("User nicht vorhanden")
        elif len(email) < 4:
            flash("E-Mail zu kurz (<3)", category="error")
        elif len(first_name) < 2:
            flash("Name zu kurz (<2)", category="error")
        elif len(last_name) < 2:
            flash("Name zu kurz (<2)", category="error")
        elif current_user.admin == 0:
            if check_password_hash(user.password, old_pw) != True:
                flash("Aktuelles Passwort falsch!", category="error")
                # return redirect(request.referrer)
                # ?
        elif (
            password1 == None or password1 == "" and password2 == ""
        ):  # pw fields empty
            user.update(email, first_name, last_name, admin)
            db.session.commit()
            flash("Benutzer bearbeitet!", category="success")
            return redirect(url_for("users.users"))
            # return redirect(request.referrer)

        elif password1 != password2:
            flash("Pw stimmt nicht überein", category="error")
        elif len(password1) < 3:
            flash("PW zu kurz(<3)", category="error")
            # return redirect(request.referrer)
        else:
            user.update(
                email,
                first_name,
                last_name,
                admin,
                generate_password_hash(password1, method="sha256"),
            )
            db.session.commit()
            flash("Benutzer bearbeitet!", category="success")
            # return redirect(url_for("users.users"))
            return redirect(request.referrer)
    user = User.query.get(user_id)
    print(user)
    return render_template("users/users_c_u.html", current_user=current_user, user=user)


@users.route("/users/create", methods=["GET", "POST"])
@login_required
def user_create():
    """View function to create a new User"""
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        last_name = request.form.get("lastName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        admin = request.form.get("admin")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email in Benutzung", category="error")
            return redirect(request.referrer)
        elif len(email) < 4:
            flash("E-Mail zu kurz (<3)", category="error")
            return redirect(request.referrer)
        elif len(first_name) < 2:
            flash("Name zu kurz (<1)", category="error")
            return redirect(request.referrer)
        elif password1 != password2:
            flash("Pw stimmt nicht überein", category="error")
            return redirect(request.referrer)
        elif len(password1) < 3:
            flash("PW zu kurz(<3)", category="error")
            return redirect(request.referrer)
        else:
            new_user = User(
                email=email,
                first_name=first_name,
                last_name=last_name,
                admin=admin,
                password=generate_password_hash(password1, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            flash("Benutzer angelegt!", category="success")
        return redirect(url_for("users.users_view"))
    return render_template(
        "users/users_c_u.html", current_user=current_user, user=False
    )


@users.route("/users/<int:user_id>/delete", methods=["GET"])
@login_required
def user_delete(user_id):
    """View function to delete a User"""
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash("Benutzer entfernt!", category="success")
        return redirect(url_for("users.users_view"))
    flash(f"Benutzer ID {user_id} nicht vorhanden!", category="error")
    return redirect(url_for("users.users_view"))

fahrplan/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}">
       <!-- <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="/website/static/favicon-32x32.png"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <title>
        {% block title %}Fahrplan-IS{% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <a class="nav-link nav-item"
               href="{{ url_for('index.index_view') }}">
                <div class="navbar-brand">
                    <img src="{{ url_for('static', filename='favicon.ico') }}"
                         alt="F">ahrplan-Informationssystem
                </div>
            </a>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link"
                id="fahrplan"
                href="{{ url_for('lines.lines_view') }}">Fahrtstrecken</a>
                {% if current_user.admin == 1 %}
                <a class="nav-item nav-link"
                   id="users"
                   href="{{ url_for('users.users_view') }}">Personal</a>
                   {% endif %}
                   <a class="nav-item nav-link"
                      id="users"
                      href="{{ url_for('users.user_trips', user_id=current_user.id) }}">Meine Fahrten</a>

                {% endif %}
            </ul>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                <!-- "&#128129; &#128572; -->
                <span style="font-size: 1.5em;"><img alt="&#127774;"
                         src="{{ url_for('static', filename='avatar/avatar.svg') }}" /></span>
                <!-- <a href="users/{{ current_user.id }}" -->
                <a href="{{ url_for('users.user_update', user_id=current_user.id) }}"
                   class="nav-item nav-link">
                    {{ current_user.first_name }} {{ current_user.last_name }}
                    {% if current_user.admin == 1%}(Admin){% endif %}
                </a>
                <a class="nav-item nav-link"
                   id="logout"
                   href="{{ url_for('auth.logout') }}">
                    Logout
                </a>
                {% else %}
                <a class="nav-item nav-link"
                   id="login"
                   href="{{ url_for('auth.login') }}">Login</a>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable show"
         role="alert">
        {{ message }}
        <button type="button"
                class="close"
                data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif category == 'success' %}
    <div class="alert alert-success alert-dismissable show"
         role="alert">
        {{ message }}
        <button type="button"
                class="close"
                data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>


    <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <!-- <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li> -->
            </ul>
            <p class="text-center text-muted">Your Getaway FAHRPLAN</p>
            <p class="text-center text-muted">Simon Mittermair</p>
        </footer>
    </div>

</body>

</html>

fahrplan/website/templates/fahrplan.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrpläne{% endblock %}
{% block content %}
<h1 class="py-4">Fahrpläne</h1>


{% if current_user.admin == 1 %}
<a href="create"
   class="btn btn-outline-primary">Neue Fahrtstrecke hinzufügen</a>
<p></p>
<table class="table">
    <thead>
        <tr>
            <!-- <th scope="col">&#x2666;</th> -->
            <th scope="col">#</th>
            <th scope="col">Fahrtstrecke</th>
            <th scope="col">auf Strecke</th>
            <th scope="col">von</th>
            <th scope="col">nach</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for line in lines %}
        <!-- if line.sections - workaround fur unvollstandige daten -->
        {% if line.sections %}
        <tr>
            <th scope="row"
                data-id="{{ line.id }}">{{ line.id }}</th>
            <td data-id="{{ line.id }}">{{ line.description }}</td>
            <td data-id="{{ line.id }}">{{ line.route_name }}</td>
            <td data-id="{{ line.id }}">{{ line.sections | first | attr('from_station_name') }}</td>
            <td data-id="{{ line.id }}">{{ line.sections | last | attr('to_station_name') }}</td>
            <td data-id="{{ line.id }}"> // </td>
            <td data-id="{{ line.id }}">
                <a href="./{{ line.id }}">> Durchführungen</a>
            </td>
            <td>
                <a href="{{ line.id }}"
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x270E;</span>
                </a>
            </td>
            <td>
                <a href="{{ line.id }}/delete"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                    <!-- <span aria-hidden="true">&#x1f5d1;</span> -->
                </a>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>
    Keine Berechtigung
</p>
{% endif %}

<br>
<h2>Fahrtstrecken (groupby Strecke)</h2>
<hr>
{% for route_name, lines in lines | groupby('route_name')%}
<h3 class="border-bottom">{{ route_name }} 
    <a href="create/{{ route_name }}"
       class=" btn-sm  my-sm-2"> + Neue Fahrtstrecke hinzufügen</a>
</h3>
<ul class="list-group list-group-flush"
    id="lines-list">
    {% for line in lines %}
    <li id="{{ line.id }}"
        class="entry list-group-item">
        <span>{{ line.description }}</span>
        <a href="./{{ line.id }}">> Durchführungen</a>
    </li>
    {% endfor %}
</ul>
{% endfor %}
{% endblock %}

fahrplan/website/templates/index.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Home{% endblock %}
{% block content %}
<h1 class="py-4">Fahrplan</h1>
{% if not current_user.is_authenticated %}
<p>Bitte einloggen um fortzufahren.</p>
{% endif %}
<h2 class="py-1"></h2>

{% for line in lines %}
{% include 'lines/line_component.html' %}
{% include 'trips/trips_component.html' %}
{% endfor %}

{% endblock %}

fahrplan/website/templates/lines.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Fahrpläne{% endblock %}
{% block content %}
<h1 class="py-5">Fahrtstrecken</h1>


{% if user.admin == 1 %}
<a href="create"
   class="btn btn-outline-primary">Neue Fahrtstrecke hinzufügen</a>
<p></p>
<table class="table">
    <thead>
        <tr>
            <!-- <th scope="col">&#x2666;</th> -->
            <th scope="col">#</th>
            <th scope="col">Fahrtstrecke</th>
            <th scope="col">auf Strecke</th>
            <th scope="col">von</th>
            <th scope="col">nach</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for line in lines %}
        <!-- if line.sections - workaround fur unvollstandige daten -->
        {#% if line.sections %#}
        <tr>
            <th scope="row"
                data-id="{{ line.id }}">{{ line.id }}</th>
            <td data-id="{{ line.id }}">{{ line.descr }}</td>
            <td data-id="{{ line.id }}">{{ line.route.name }}</td>
            <td data-id="{{ line.id }}">{{ (line.sections | first).section.from_station_name }}</td>
            <td data-id="{{ line.id }}">{{ (line.sections | last).section.to_station_name }}</td>
            <td data-id="{{ line.id }}"> // </td>
            <td data-id="{{ line.id }}">
                <a href="./{{ line.id }}">> Durchführungen</a>
            </td>
            <td>
                <a href="{{ line.id }}"
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x1f589;</span>
                </a>
            </td>
            <td>
                <a href="{{ line.id }}/delete"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                    <!-- <span aria-hidden="true">&#x1f5d1;</span> -->
                </a>
            </td>
        </tr>
        {#% endif %#}
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>
    Keine Berechtigung
</p>
{% endif %}

{% if False %}
<br>
<h2>Fahrtstrecken (groupby Strecke)</h2>
<hr>
{% for route, line in lines | groupby('route.name') %}
<h3 class="border-bottom">{{ route.name }} 
    <a href="create/{{ route.name }}"
       class=" btn-sm  my-sm-2"> + Neue Fahrtstrecke hinzufügen</a>
</h3>
<ul class="list-group list-group-flush"
    id="lines-list">
    {% for line in lines %}
    <li id="{{ line.id }}"
        class="entry list-group-item">
        <span>{{ line.description }}</span>
        <a href="./{{ line.id }}">> Durchführungen</a>
    </li>
    {% endfor %}
</ul>

{% endfor %}
{% endif %}
{% endblock %}

fahrplan/website/templates/login.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Login{% endblock %}
{% block content %}
<form method="post">
    <h3>Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input required
               type="email"
               class="form-control"
               id="email"
               name="email"
               placeholder="Enter Email Address">
        <label for="password">password1</label>
        <input required
               type="password"
               class="form-control"
               id="password"
               name="password"
               placeholder="Enter Password">
        <br>
        <button type="submit"
                class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

fahrplan/website/templates/users.html
{% extends "base.html" %}
{% block title %}Fahrplan-IS - Personal{% endblock %}
{% block content %}
<h1>Personal</h1>
{% if user.admin == 1 %}
<table class="table">
    <thead>
        <tr>
            <!-- <th scope="col">&#x1F511;</th> -->
            <th scope="col">&#x2666;</th>
            <th scope="col">#</th>
            <th scope="col">Vorname</th>
            <th scope="col">Nachname</th>
            <th scope="col">Email</th>
            <th scope="col">Geburtsdatum</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for u in users %}
        <tr>
            {% if u.admin == 1 %}
            <!-- <td><span><i class="fa-solid fa-key"></i></span></td> -->
            <td>&#x1F511;</td>
            <!-- <td>&#x1F510;</td> -->
            {% else %}
            <td></td>
            {% endif %}
            <th scope="row"
                data-id="{{ u.id }}">{{ u.id }}</th>
            <td data-id="{{ u.id }}">{{ u.first_name }}</td>
            <td data-id="{{ u.id }}">{{ u.last_name }}</td>
            <td data-id="{{ u.id }}">{{ u.email }}</td>
            <td data-id="{{ u.id }}">{{ u.birthday }}</td>
            <td>
                <a href="{{ u.id }}"
                   id="btn-edit"
                   class="btn btn-sm btn-outline-secondary"
                   aria-label="Edit">
                    <span aria-hidden="true">&#x1f589;</span>
                </a>
            </td>
            <td>
                <a href="{{ u.id }}/delete"
                   id="btn-delete"
                   class="btn btn-sm btn-outline-danger"
                   aria-label="Delete">
                    <span aria-hidden="true">&#x2A09;</span>
                    <!-- <span aria-hidden="true">&#x1f5d1;</span> -->
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="create"
   class="btn btn-outline-primary">Weiteren Personalaccount hinzufügen</a>
{% else %}
<p>
    Keine Berechtigung
</p>
{% endif %}
{% endblock %}